---
<<<<<<< HEAD
title: "Problem Set template"
author: "Fernanda Sobrino"
date: "29/03/2020"
=======
title: "Applied Problem Set 1"
author: "Ryan McGinnis and Vera Jonsdottir"
date: "4/22/2021"
>>>>>>> 9c89b7f7411bfae0667e9669b51c141c7e12337f
output: 
  pdf_document:
    number_sections: yes
  html_document:
    df_print: paged
urlcolor: blue
---
```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tibble)
library(dplyr)
library(ggplot2)
```


2.1.1. 

```{r}
library(readr)
trips_mcma <- read_csv("trips_mcma.csv")
```

2.1.2 

```{r echo=FALSE}
print(trips_mcma)
head(trips_mcma)
str(trips_mcma)
glimpse(trips_mcma)
view(trips_mcma)
summary(trips_mcma)
```

2.1.2.1
str and glimpse are quite similar
head is technically redundant but it is just more condensed.
2.1.2.2

2.2.1
```{r}
#The data has 531594 rows and 20 columns
nrow(trips_mcma)
ncol(trips_mcma)
#id_trip is the unique identifier.
#each row represents different (unique) bike rides over a set of indicators. 
```
2.2.2
```{r}
# Applying group_by & summarise
 trips_mcma %>%                              
  summarise(count = n_distinct(state_origin))
```

```{r}
trips_mcma %>%
  drop_na(state_origin, state_dest) %>%
  count()

```

2.2.3
```{r}
trips_mcma %>%                              
  group_by(mode_trans) %>%   
  summarise(count = n_distinct((trips_mcma$mode_trans))) %>%
  arrange(desc(count))
```

2.2.4
```{r}
trips_mcma %>%  
  count(reason, sort=TRUE)
  

```
The five least common reasons for trips are church, other, errands, health, and
leisure

2.2.5
```{r}
trips_mcma %>% 
  group_by(day)%>%
  summarise(count=n()) %>%
  mutate(percent = count/sum(count))

```

2.2.6
```{r}
trips_mcma %>%
mutate(minutes = (arr_hour - dep_hour)*60 + arr_min - dep_min) %>%
  drop_na(minutes) %>%
   summarize(mean_minutes = mean(minutes, na.rm = TRUE))
```



```{r}
trips_mcma$minutes <- (trips_mcma$arr_hour - trips_mcma$dep_hour)*60 + trips_mcma$arr_min - trips_mcma$dep_min
glimpse(trips_mcma)
ggplot(trips_mcma, aes(x = minutes),binwidht=1)+
         geom_histogram()+
  xlim(-5,200)
```
2.3

2.3.1
```{r}
glimpse(trips_mcma)

#trips within mexico city


trips_mcma %>%
  drop_na(state_origin, state_dest) %>%
  drop_na(mun_origin,mun_dest) %>%
  filter(state_origin==9 & state_dest==9) %>%
  count()


#trips within mexico city and municipalities
trips_mcma %>%
  drop_na(state_origin, state_dest,mun_origin,mun_dest) %>%
  filter(state_origin==9 & state_dest==9 ,  mun_origin==mun_dest) %>%
  count

#trips within municipalities (not necessarily in mexico city)

trips_mcma %>%
  drop_na(mode_trans) %>%
  #filter( ) %>%
  count


```

2.3.2
```{r}


head(trips_mcma,100)

# lengt of tips
trips_mcma %>%
mutate(minutes = (arr_hour - dep_hour)*60 + arr_min - dep_min) %>%
  drop_na(minutes) %>%
   summarize(mean_minutes = mean(minutes, na.rm = TRUE))


#length of biking trips
trips_mcma %>%
mutate(minutes = (arr_hour - dep_hour)*60 + arr_min - dep_min) %>%
  drop_na(minutes) %>%
  filter(mode_trans=="Bike") %>%
   summarize(mean_minutes = mean(minutes, na.rm = TRUE))


#plot of pikers time
ggplot(subset(trips_mcma, mode_trans=="Bike"), aes(x = minutes),binwidht=1)+
         geom_histogram()+
  xlim(-5,200)

```
5.3.3

```{r}
trips_mcma %>%
  drop_na(mode_trans) %>%
  group_by(mode_trans) %>%
  filter(mun_origin==mun_dest) %>%
  summarise(count=n()) %>%
  mutate(percent = count/sum(count))

```
5.3.4
```{r}
ggplot(subset(trips_mcma), aes(x = dep_hour),binwidht=1)+
         geom_histogram()


```
5.3.5
```{r}

glimpse(trips_mcma)

trips_mcma %>%
  drop_na(sex) %>%
  group_by(sex,mode_trans) %>%
  summarise(count=n()) %>%
  mutate(percent = count/sum(count))


trips_mcma %>%
  drop_na(age) %>%
  group_by(age,mode_trans) %>%
  summarise(count=n()) %>%
  mutate(percent = count/sum(count))

```

